---
abstract: 'Easy way to use String::TT in Dancer apps'
author:
  - 'Benjamin Stier (ben@unpatched.de)'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer-Plugin-String-TT
no_index:
  directory:
    - t
    - inc
requires:
  Test::Simple: 0.44
version: 0.01
